---
- name: Configure network {{ adrianjuhl__openstack_network__network_name }}
  os_network:
    auth: "{{ adrianjuhl__openstack_network__auth }}"
    name: "{{ adrianjuhl__openstack_network__network_name }}"
    state: present
  register: network_result
- debug:
    msg: "network_result: {{ network_result }}"
    verbosity: 2
- name: Create subnet {{ adrianjuhl__openstack_network__subnet_name }}
  os_subnet:
    auth: "{{ adrianjuhl__openstack_network__auth }}"
    name: "{{ adrianjuhl__openstack_network__subnet_name }}"
    state: present
    network_name: "{{ adrianjuhl__openstack_network__network_name }}"
    cidr: 10.0.0.0/24
    dns_nameservers: "{{ adrianjuhl__openstack_network__nameservers }}"
  register: subnet_result
- debug:
    msg: "subnet_result: {{ subnet_result }}"
    verbosity: 2
- name: Create router {{ adrianjuhl__openstack_network__router_name }}
  os_router:
    auth: "{{ adrianjuhl__openstack_network__auth }}"
    name: "{{ adrianjuhl__openstack_network__router_name }}"
    state: present
    network: "{{ adrianjuhl__openstack_network__network_name }}"
    interfaces:
      - "{{ adrianjuhl__openstack_network__subnet_name }}"
  register: router_result
- debug:
    msg: "router_result: {{ router_result }}"
    verbosity: 2
