---
# tasks file for adrianjuhl.openstack_network

- debug:
    msg: "hello, world new"
#    verbosity: 2

- name: Configure network, subnet, and router
  include_tasks: configure_network_subnet_router.yml

- debug:
    msg: "after network configured"
